package com.spa.home_rental_application.lease_service.service;

import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;
import com.spa.home_rental_application.lease_service.Entities.Lease;
import com.spa.home_rental_application.lease_service.Exceptionclass.LeaseDeedException;
import com.spa.home_rental_application.lease_service.config.LeaseProperties;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.format.DateTimeFormatter;

/**
 * Renders a single-page lease deed PDF including the RERA agreement number
 * resolved from Compliance Service. Output written to the configured local
 * dir for now — swap to S3 in production.
 */
@Component
@Slf4j
public class LeaseDeedPdfGenerator {

    private static final DateTimeFormatter DATE = DateTimeFormatter.ISO_LOCAL_DATE;

    private final LeaseProperties props;

    public LeaseDeedPdfGenerator(LeaseProperties props) {
        this.props = props;
    }

    /** Returns the absolute path of the generated PDF. */
    public String generate(Lease lease, String reraStamp) {
        Path dir = Paths.get(props.getDeedStorageDir());
        try {
            Files.createDirectories(dir);
        } catch (IOException e) {
            throw new LeaseDeedException("Cannot create lease deed dir: " + dir, e);
        }
        Path file = dir.resolve(lease.getLeaseNumber() + ".pdf");

        try (OutputStream os = Files.newOutputStream(file)) {
            Document document = new Document();
            PdfWriter.getInstance(document, os);
            document.open();

            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16, Font.BOLD);
            Paragraph title = new Paragraph("LEASE / RENT AGREEMENT", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);
            document.add(new Paragraph(" "));

            Font normal = FontFactory.getFont(FontFactory.HELVETICA, 11);
            Font bold = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11);

            document.add(new Paragraph("Lease No: " + lease.getLeaseNumber(), bold));
            document.add(new Paragraph(reraStamp == null ? "RERA: pending" : reraStamp, normal));
            document.add(new Paragraph(" "));

            document.add(new Paragraph("Owner ID: " + lease.getOwnerId(), normal));
            document.add(new Paragraph("Tenant ID: " + lease.getTenantId(), normal));
            document.add(new Paragraph("Flat ID: " + lease.getFlatId(), normal));
            document.add(new Paragraph(" "));

            document.add(new Paragraph(
                    "Term: " + DATE.format(lease.getStartDate())
                            + " to " + DATE.format(lease.getEndDate()), normal));
            document.add(new Paragraph(
                    "Monthly Rent: INR " + lease.getRentAmount().toPlainString(), normal));
            if (lease.getSecurityDeposit() != null) {
                document.add(new Paragraph(
                        "Security Deposit: INR " + lease.getSecurityDeposit().toPlainString(), normal));
            }
            if (lease.getRentIncrementPercent() != null) {
                document.add(new Paragraph(
                        "Annual rent increment: " + lease.getRentIncrementPercent() + " %", normal));
            }
            document.add(new Paragraph(" "));
            document.add(new Paragraph(
                    "Digital signature status: " + lease.getDigitalSignatureStatus(), normal));
            document.add(new Paragraph(" "));
            document.add(new Paragraph(
                    "This deed is generated by RentGenius and is legally binding upon both parties "
                            + "subject to RERA and applicable Indian rental laws.",
                    FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 9)));

            document.close();
            log.info("Generated lease deed PDF: {}", file);
            return file.toAbsolutePath().toString();
        } catch (IOException e) {
            throw new LeaseDeedException("Failed to write lease deed PDF: " + file, e);
        }
    }
}
