package com.spa.home_rental_application.kyc_service.provider;

import com.spa.home_rental_application.kyc_service.DTO.Request.InitiateKycRequest;
import com.spa.home_rental_application.kyc_service.config.KycProperties;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Component;
import org.springframework.web.util.UriComponentsBuilder;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.security.SecureRandom;
import java.util.Base64;

/**
 * Production KYC backend that talks to DigiLocker (MeitY) via OAuth 2.0.
 *
 * <p>Flow (per the DigiLocker partner integration guide v1.3):
 * <ol>
 *   <li>{@link #initiate} returns an authorize URL the user's browser is
 *       sent to. Includes a {@code state} parameter for CSRF protection —
 *       generated by KycServiceImpl, persisted on the KYC record, and
 *       echoed back here.</li>
 *   <li>User logs in at DigiLocker, grants consent, and is redirected
 *       back to {@code redirectUri?code=…&state=…}.</li>
 *   <li>The frontend hands {@code code+state} back to our server, which
 *       calls {@link DigiLockerOAuthClient#exchangeCodeForToken} +
 *       {@link DigiLockerOAuthClient#fetchEAadhaarXml}, then
 *       {@link EAadhaarXmlParser#parse}.</li>
 *   <li>The KYC record flips to VERIFIED and {@code kyc.verified} is
 *       published. The Aadhaar number is hashed at this point — only
 *       the hash + last-4 ever land in our DB.</li>
 * </ol>
 *
 * <p>Activates only when {@code app.kyc.provider=DIGILOCKER}. Sits next
 * to {@link DigioKycProvider} (legacy) and {@link MockKycProvider}
 * (dev/CI); Spring picks one based on the config switch.
 *
 * <p>DigiLocker does not expose a standalone PAN-verify API, so
 * {@link #verifyPan} always returns "not supported" — the standalone
 * PAN flow on our KYC page should redirect users to use the full
 * DigiLocker flow instead.
 */
@Component
@ConditionalOnProperty(prefix = "app.kyc", name = "provider", havingValue = "DIGILOCKER")
@Slf4j
public class DigiLockerProvider implements KycProvider {

    /** Cryptographic RNG for OAuth state token generation. Thread-safe. */
    private static final SecureRandom SECURE_RANDOM = new SecureRandom();

    private final KycProperties props;

    public DigiLockerProvider(KycProperties props) {
        this.props = props;
    }

    @Override
    public String name() {
        return "DIGILOCKER";
    }

    /**
     * Builds the authorize URL the user's browser should be redirected to.
     *
     * <p>The caller (KycServiceImpl) is responsible for generating + persisting
     * the {@code state} value first — we just plug it into the URL.
     * The persisted state is what we cross-check on callback to defeat
     * CSRF (RFC 6749 §10.12) and to recover which userId the callback
     * belongs to.
     *
     * <p>The {@code referenceId} we return is the state itself — it
     * doubles as our correlation id and the OAuth state. KycServiceImpl
     * persists it to {@code kyc_records.kyc_reference_id}.
     */
    @Override
    public InitiateResult initiate(String userId, InitiateKycRequest request) {
        String state = newStateToken();
        String authorizeUrl = UriComponentsBuilder
                .fromHttpUrl(props.getDigilocker().getAuthorizeUrl())
                .queryParam("response_type", "code")
                .queryParam("client_id", props.getDigilocker().getClientId())
                .queryParam("redirect_uri",
                        URLEncoder.encode(props.getDigilocker().getRedirectUri(), StandardCharsets.UTF_8))
                .queryParam("state", state)
                .build(true)         // value-encoded above — don't double-encode
                .toUriString();

        log.info("DigiLocker initiate userId={} state={} authorizeUrl={}", userId, state, authorizeUrl);
        return new InitiateResult(state, "PENDING", authorizeUrl);
    }

    /**
     * DigiLocker doesn't expose a standalone PAN-verification API; PAN
     * details flow through the eAadhaar/eKYC document instead. We return
     * an explicit "not supported" failure so the caller can surface a
     * clean message rather than blocking the user.
     */
    @Override
    public PanResult verifyPan(String panNumber, String panHolderName) {
        log.info("DigiLocker verifyPan called — not supported by DigiLocker, returning failure");
        return new PanResult(false, panHolderName,
                "PAN verification via DigiLocker is unsupported — use the full DigiLocker flow.");
    }

    /**
     * 256-bit URL-safe token used as the OAuth state parameter. Length is
     * 43 chars (Base64URL without padding) — well within the 512-byte
     * limit most OAuth providers enforce, and large enough that brute
     * force isn't viable.
     */
    static String newStateToken() {
        byte[] bytes = new byte[32];
        SECURE_RANDOM.nextBytes(bytes);
        return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);
    }
}
