package com.spa.home_rental_application.property_service.property_service.service.impl;

import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Image;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;
import com.spa.home_rental_application.property_service.property_service.Entities.Agreement;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Base64;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Renders a single-page A4 lease agreement PDF using OpenPDF and embeds the
 * tenant's drawn signature (which is a base64 PNG from the canvas pad).
 *
 * <p>Output is written to {@code app.agreements.deed-storage-dir} (default
 * {@code uploads/lease-deeds-property}). Same convention as Lease Service —
 * one volume per service so a single Document Service migration later can
 * pull both into S3 with no code change to either.
 */
@Component
@Slf4j
public class AgreementPdfGenerator {

    private static final Pattern DATA_URL_PNG =
            Pattern.compile("^data:image/(?:png|jpeg);base64,(.*)$");

    @Value("${app.agreements.deed-storage-dir:uploads/lease-deeds-property}")
    private String storageDir;

    /**
     * Renders the agreement and returns the absolute path of the PDF on disk.
     * Throws an unchecked exception on I/O / OpenPDF failures — callers
     * (AgreementServiceImpl.sign) treat the PDF rendering as best-effort
     * and let the lease still be SIGNED even if PDF generation fails.
     */
    public String render(Agreement agreement) {
        Path dir = Paths.get(storageDir);
        try {
            Files.createDirectories(dir);
        } catch (IOException e) {
            throw new IllegalStateException("Cannot create deed dir: " + dir, e);
        }
        Path file = dir.resolve(agreement.getId() + ".pdf");

        try (OutputStream os = Files.newOutputStream(file)) {
            Document doc = new Document();
            PdfWriter.getInstance(doc, os);
            doc.open();

            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16, Font.BOLD);
            Paragraph title = new Paragraph("RESIDENTIAL LEASE AGREEMENT", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            doc.add(title);
            doc.add(new Paragraph(" "));

            Font normal = FontFactory.getFont(FontFactory.HELVETICA, 11);
            Font label = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11);

            doc.add(new Paragraph("Agreement No: " + agreement.getId(), label));
            doc.add(new Paragraph("Owner ID: " + nullSafe(agreement.getOwnerId()), normal));
            doc.add(new Paragraph("Tenant ID: " + nullSafe(agreement.getTenantId()), normal));
            doc.add(new Paragraph("Flat ID: " + nullSafe(agreement.getFlatId()), normal));
            doc.add(new Paragraph(" "));
            doc.add(new Paragraph(
                    "Term: " + agreement.getLeaseStartDate() + " to " + agreement.getLeaseEndDate(),
                    normal));
            doc.add(new Paragraph(
                    "Monthly Rent: INR " +
                            (agreement.getRentAmount() == null ? "-"
                                    : agreement.getRentAmount().toPlainString()),
                    normal));
            doc.add(new Paragraph(" "));

            // Body — terms verbatim
            Font small = FontFactory.getFont(FontFactory.HELVETICA, 10);
            String terms = agreement.getTerms() == null ? "" : agreement.getTerms();
            // OpenPDF doesn't auto-respect \n in a single Paragraph — split.
            for (String line : terms.split("\\r?\\n")) {
                doc.add(new Paragraph(line.isEmpty() ? " " : line, small));
            }

            doc.add(new Paragraph(" "));
            doc.add(new Paragraph(" "));
            doc.add(new Paragraph(
                    "Signed at " +
                            (agreement.getSignedAt() == null ? "—" : agreement.getSignedAt()),
                    normal));

            // Embed the signature PNG
            embedSignature(doc, agreement.getSignatureData());

            doc.add(new Paragraph(" "));
            doc.add(new Paragraph(
                    "This deed is generated by the RentGenius platform. "
                            + "Both parties have agreed to the above terms electronically.",
                    FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 9)));

            doc.close();
            log.info("Rendered agreement PDF {}", file);
            return file.toAbsolutePath().toString();
        } catch (IOException e) {
            throw new IllegalStateException("Failed to write deed PDF: " + file, e);
        }
    }

    private void embedSignature(Document doc, String signatureData) {
        if (signatureData == null || signatureData.isBlank()) return;
        try {
            String base64 = signatureData;
            Matcher m = DATA_URL_PNG.matcher(signatureData);
            if (m.find()) base64 = m.group(1);
            byte[] bytes = Base64.getDecoder().decode(base64);
            Image img = Image.getInstance(bytes);
            img.scaleToFit(180, 80);
            doc.add(new Paragraph("Tenant signature:",
                    FontFactory.getFont(FontFactory.HELVETICA, 10)));
            doc.add(img);
        } catch (Exception e) {
            // Bad signature data — ship a textual placeholder rather than
            // failing the whole PDF.
            log.warn("Signature embed failed: {}", e.getMessage());
            try {
                doc.add(new Paragraph("[Signature on file — could not render image]",
                        FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 10)));
            } catch (Exception ignored) {
                /* doc closed — give up silently */
            }
        }
    }

    private String nullSafe(String s) {
        return s == null ? "—" : s;
    }
}
